id: 7da4b4352cfa446691118b81314ef446
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_729-Dh%C4%81ra%E1%B9%87%C4%AB_of_T%C4%81r%C4%81-v2.bo.en
  language: bo
  author: ''
  volume: {}
